version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://<username>:<password>@mongodb:27017/password_manager
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:300"
    depends_on:
      - backend
