version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: password-mongodb-1
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: password-backend-1
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app
    command: nodemon src/server.ts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: password-frontend-1
    ports:
      - "5001:5001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    command: npm start

volumes:
  mongodb_data:
